### DISCUSSION TITLE
Install Spack + Quantum ESPRESSO on MacOS

### DISCUSSION THREAD

**Discussion by nguyen-group** [nguyen-group/QE-SSP#9] [General]
### 1) Install Brew (https://brew.sh/):
```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

### 2) Install GCC from Brew:
```
$ brew install gcc
```
Check GCC version:
```
$ brew info gcc
```
You will see something like:
```
==> gcc: stable 15.1.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
Installed
```

### 3) Install Spack from Brew:
```
$ brew install spack
```

### 4) Find the compiler in spack:
```
$ spack compiler find
```

### 5) Checklist of compilers
```
$ spack compilers
```
You will see something like:
```
==> Available compilers
-- apple-clang sequoia-aarch64 ----------------------------------
apple-clang@17.0.0

-- gcc sequoia-aarch64 ------------------------------------------
gcc@15.1.0
```
Note: If you install Xcode, apple-clang@17.0.0 will be found by Spack. If Xcode is not installed, we will find only gcc@15.1.0
### 6) Install openblas, curl, krb5, and cmake using brew 
Note: these packages might not install successfully with spack. Thus, we use brew instead; it can also apply to other packages.
```
$ brew install openblas curl krb5 cmake git fftw scalapack open-mpi
```
Then, add these packages to spack as
```
$ spack config edit packages
```
Then, update the information as follows:
```
packages:
  all:
    compiler: [gcc]
  openblas:
    buildable: false
    externals:
    - spec: openblas@0.3.30
      prefix: /opt/homebrew/opt/openblas
  curl:
    buildable: false
    externals:
    - spec: curl@8.14.1
      prefix: /opt/homebrew/opt/curl
  krb5:
    buildable: false
    externals:
    - spec: krb5@1.21.3
      prefix: /opt/homebrew/opt/krb5
  cmake:
    buildable: false
    externals:
    - spec: cmake@4.0.3
      prefix: /opt/homebrew/opt/cmake
  git:
    buildable: false
    externals:
    - spec: git@2.50.0
      prefix: /opt/homebrew/opt/git
  fftw:
    buildable: false
    externals:
    - spec: fftw@3.3.10
      prefix: /opt/homebrew/opt/fftw
  scalapack:
    buildable: false
    externals:
    - spec: scalapack@2.2.2
      prefix: /opt/homebrew/opt/scalapack
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@5.0.7
      prefix: /opt/homebrew/opt/open-mpi   
```
Save the file by press Esc key, type :w and hit Enter key.
Note: the version of each package can be found by using the command:
```
$ brew info openblas
```

### 7) Install Quantum ESPRESSO
```
$ spack install  quantum-espresso
```
Or install with a specific version and compiler
```
$ spack install  quantum-espresso@7.2 %gcc
```
